### PR TITLE
Added Border Arrows 

### LINKED ISSUE #17: Change Meet The Team Slider Arrows Position
- [x] Add the slider arrows to the right and left of the carousel such that there is no overlap over the picture

### PR DESCRIPTION
**Pull request by vvkash**

### CODE REVIEW

**Comment by vvkash** [comment]
For some reason some time the arrows are responsive and sometimes there not lol, im not sure if this an issue only on my end or not. please lmk!

Also, what was that issue regarding the banner for the homepage? i forgot haha

**Comment by aryasalian** [comment]
First, pull from origin/dev-phase and make a merge request into dev-phase, not github-pages. Next, as for the arrows I'm looking into it right now and editing the code a bit to try and fix it. I'll comment out things, not delete them. Finally for the banner resizing, I was talking about getting the MLH banner in the top right corner to not cover any text at any window size. Also, the Meet The Team button on the homepage's navbar is not yet fixed. Please ensure resizing problems on that are resolved too.

**Comment by aryasalian** [comment]
With that commit the arrow issue is completely fixed and the scroll is elegant. There is no extra space in the last button click.

Fix the resizing issues and do all the pull stuff too. Also when you pull from origin/dev you should see we have made a new CSS file for meet-the-team. Shift all your CSS code to that instead of keeping it in the HTML code. Everything else seems good to me!

**Comment by aryasalian** [comment]
This will still be needed, just not now.

**Review by aryasalian — APPROVED** [review]

**Pull request merged**
